


SELECT * 
FROM TBDOCUMENTOS
WHERE IDTIPODOCU = 215 
ORDER BY 1 DESC


SELECT * FROM TBDOCUMENTOS WHERE SERIDOCU = '20198858' AND NUMEDOCU = '314'
--55611


SELECT * FROM TBCAJAS WHERE IDDOCUMENTOCAJA = 55611

SELECT * FROM TBDOCUMENTOS WHERE SERIDOCU = '20198858' AND NUMEDOCU = '314'


SELECT TBDOCUMENTOS.* 
FROM TBDOCUMENTOS 
INNER JOIN TBCAJAS ON TBCAJAS.IDDOCUMENTOOPERACION = TBDOCUMENTOS.IDDOCUMENTO
WHERE TBCAJAS.IDDOCUMENTOCAJA IN 
(SELECT IDDOCUMENTO FROM TBDOCUMENTOS WHERE SERIDOCU = '20198858' AND NUMEDOCU = '314')


SELECT * FROM TBDETCOMERCIAL

--55613

SELECT * FROM TBDETCOMERCIAL WHERE IDDOCUMENTO = 55613









